title: Elora Robeck
description: Website for Elora Robeck

url: https://elrob5.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: elrob5
    twitter: #brianmaierjr
    facebook: #brianmaierjr
    email: erobeck@ucdavis.edu
    linkedin: www.linkedin.com/in/elora-robeck-ab0037275
    youtube: #RickAstleyYT
    tumblr: #i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: elrobeck
